name: comic_cover_generator
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - pytorch::cpuonly
  - pip>=22.0.4
  - pip:
      - -e '.[dev]'
