defaults:
  - dataset: cover_dataset
  - model: gan
  - _self_

logger:
  tracking_uri: "file://${hydra:runtime.cwd}/experiment_outputs/mlruns/"

trainer:
  default_root_dir: "${hydra:runtime.cwd}/experiment_outputs"
  max_steps: 10000
  gpus: 0
  amp_backend: "apex"
  auto_lr_find: False
  auto_scale_batch_size: binsearch
  gradient_clip_val: 0.5
  enable_progress_bar: True
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: "{epoch}-{fid:.2f}"
      monitor: "fid"
      mode: "min"
      save_top_k: 1
      save_weights_only: True

# strategy
training_strategy_params:
  cls: "${get_cls: comic_cover_generator.ml.model.training_strategy.wgan_gp.WGANPlusGPTrainingStrategy}"
  kwargs:
    gradient_penalty_coef: 10.0
    critic_update_interval: 1
