defaults:
  - dataset: cover-dataset
  - model: gan
  - _self_

transformer_model: "prajjwal1/bert-tiny"

dataset_split:
  train_portion: 0.95
  val_portion: 0.05
  seed: 42

training:
  mixed_precision: True
  checkpoint_path: ${hydra:runtime:.cwd}/experiment_outputs/checkpoints/model.ckpt
  batch_size: 32
  grad_clip_val: 0.5
  max_epochs: 100
  logger:
    experiment_name: "comic_cover_generator"
    tracking_uri: "file://${hydra:runtime.cwd}/experiment_outputs/mlruns/"
  collater:
    transformer_model: ${transformer_model}
    max_length: 20
  monitor: train-fid
  strategy:
    name: nsgan
    params:
      r1_interval: 16
      r1_coef: 10
      pl_beta: 0.99
      pl_interval: 4
      pl_coef: 2
