defaults:
  - dataset: cover_dataset
  - model: gan
  - _self_

batch_size: 32
steps: 100
gpu: 0
optimizer:
    generator:
      cls: torch.optim.AdamW
      kwargs:
        lr: 3e-4
        weight_decay: 0.01
    discriminator:
      cls: torch.optim.AdamW
      kwargs:
        lr: 3e-4
        weight_decay: 0.01
