# model parameters
generator_params:
    latent_dim: 256
    w_dim: 256
    conv_channels: [512, 256, 128, 64, 32]
    char_cnn_channels: [256, 256, 256]
    output_shape: [64, 64]
    mapping_network_lr_coef: 1e-2
critic_params:
    channels: [32, 64, 128, 256, 512]
    input_shape: [64, 64]

optimizer_params:
    generator:
        cls: "${get_cls: torch.optim.AdamW}"
        kwargs:
            lr: 3e-4
            betas: [0.0, 0.99]
            weight_decay: 0.0
    critic:
        cls: "${get_cls: torch.optim.AdamW}"
        kwargs:
            lr: 3e-4
            betas: [0.0, 0.99]
            weight_decay: 0.00
