# model parameters
generator:
    latent_dim: 256
    w_dim: 256
    conv_channels: [512, 256, 128, 64, 32]
    output_shape: [64, 64]
    mix_style_prob: 0.1
    transformer_model: ${transformer_model}
critic:
    channels: [32, 64, 128, 256, 512]
    input_shape: [64, 64]

optimizer:
    generator:
        opt_cls: "${get_cls: torch.optim.AdamW}"
        lr: 1e-3
        mapping_network_lr_coef: 1e-2
        betas: [0.0, 0.99]
        weight_decay: 0.0
    critic:
        opt_cls: "${get_cls: torch.optim.AdamW}"
        lr: 1e-3
        betas: [0.0, 0.99]
        weight_decay: 0.0
