name: Comic Cover Generator CI
env:
  conda_environment: "comic_cover_generator"

on:
  push:
    branches: [master, develop, "releases/**"]
  pull_request:
    branches: [master, develop, "releases/**"]

jobs:
  Test:
    name: Test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conda Cache
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Pip Cache
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{env.conda_environment}}
          environment-file: environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          auto-activate-base: false


      - name: Run Unittests
        run: PYTHONPATH=. python -m pytest tests/  -q --no-summary --no-header --tb=line
